#!/bin/sh
maxsize=$((10 * 1024 * 1024))

for file in $(git diff --cached --name-only); do
  if [ -f "$file" ]; then
    size=$(wc -c <"$file")
    if [ "$size" -gt "$maxsize" ]; then
      echo "Archivo demasiado grande: $file"
      echo "Limite: 10MB"
      exit 1
    fi
  fi
done

exit 0
